---
- name: Build NetBox device HTML report
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure reports directory exists
      ansible.builtin.file:
        path: /runner/project/reports
        state: directory
        mode: "0755"

    - name: Build HTML file
      ansible.builtin.copy:
        dest: /runner/project/reports/netbox_devices.html
        mode: "0644"
        content: |
          <html>
          <head>
            <title>NetBox Device Report</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              table { border-collapse: collapse; width: 100%; }
              th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
              th { background-color: #f2f2f2; }
              tr:nth-child(even) { background-color: #fafafa; }
            </style>
          </head>
          <body>
          <h1>NetBox Device Report</h1>
          <table>
            <tr>
              <th>Name</th>
              <th>ansible_host</th>
              <th>Role(s)</th>
              <th>Type(s)</th>
              <th>Manufacturer(s)</th>
              <th>Site(s)</th>
              <th>Region(s)</th>
              <th>Tenant(s)</th>
              <th>Primary IPv4</th>
              <th>Serial</th>
              <th>Status</th>
              <th>Tags</th>
              <th>Custom Fields</th>
            </tr>
            {% for h in groups['all'] %}
            <tr>
              <td>{{ h }}</td>
              <td>{{ hostvars[h].ansible_host | default('') }}</td>
              <td>{{ hostvars[h].device_roles | join(', ') if hostvars[h].device_roles is defined else '' }}</td>
              <td>{{ hostvars[h].device_types | join(', ') if hostvars[h].device_types is defined else '' }}</td>
              <td>{{ hostvars[h].manufacturers | join(', ') if hostvars[h].manufacturers is defined else '' }}</td>
              <td>{{ hostvars[h].sites | join(', ') if hostvars[h].sites is defined else '' }}</td>
              <td>{{ hostvars[h].regions | join(', ') if hostvars[h].regions is defined else '' }}</td>
              <td>{{ hostvars[h].tenants | join(', ') if hostvars[h].tenants is defined else '' }}</td>
              <td>{{ hostvars[h].primary_ip4 | default('') }}</td>
              <td>{{ hostvars[h].serial | default('') }}</td>
              <td>{{ hostvars[h].status.label | default('') }}</td>
              <td>{{ hostvars[h].tags | join(', ') if hostvars[h].tags is defined else '' }}</td>
              <td>
                {% if hostvars[h].custom_fields is defined %}
                  {% for k,v in hostvars[h].custom_fields.items() %}
                    {{ k }}={{ v }}<br/>
                  {% endfor %}
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </table>
          </body>
          </html>

