---
- name: Debug NetBox credential injection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show env vars from credential
      ansible.builtin.debug:
        msg:
          - "NETBOX_API (env): {{ lookup('ansible.builtin.env', 'NETBOX_API') | default('NOT SET', true) }}"
          - "NETBOX_TOKEN (env): {{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') | default('NOT SET', true) }}"

    - name: Show extra_vars from credential
      ansible.builtin.debug:
        msg:
          - "netbox_api (extra_var): {{ netbox_api | default('NOT SET', true) }}"
          - "netbox_token (extra_var): {{ netbox_token | default('NOT SET', true) }}"

