---
- name: Dump NetBox Device Data
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Print device data from webhook
      ansible.builtin.debug:
        var: device_data
        verbosity: 0
