- name: NetBox device webhook - read MAIN and print
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    # Inject via AAP Credential (env vars) or Job Template extra vars
    netbox_url: "{{ netbox_url | default(lookup('env', 'NETBOX_URL'), true) | default('', true) }}"
    netbox_token: "{{ netbox_token | default(lookup('env', 'NETBOX_TOKEN'), true) | default('', true) }}"
    netbox_validate_certs: true

  tasks:
    # ------------------------------------------------------------
    # 1) Read device ID from webhook (AAP injects extra_vars directly)
    # ------------------------------------------------------------
    - name: Assert device_data is present
      ansible.builtin.assert:
        that:
          - device_data is defined
          - device_data.id is defined
        fail_msg: "Webhook payload did not inject device_data.id into the job"

    - name: Set device_id from webhook
      ansible.builtin.set_fact:
        device_id: "{{ device_data.id }}"

    - name: Assert NetBox connection vars are present
      ansible.builtin.assert:
        that:
          - netbox_url | length > 0
          - netbox_token | length > 0
        fail_msg: "Missing netbox_url / netbox_token (AAP credential or env vars)"

    # ------------------------------------------------------------
    # 2) Fetch device from NetBox MAIN branch
    # ------------------------------------------------------------
    - name: Build NetBox device API URL (MAIN)
      ansible.builtin.set_fact:
        device_api_url: "{{ netbox_url | regex_replace('/$', '') }}/api/dcim/devices/{{ device_id }}/"

    - name: Get device from NetBox MAIN
      ansible.builtin.uri:
        url: "{{ device_api_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        return_content: true
        validate_certs: "{{ netbox_validate_certs }}"
        status_code: 200
      register: device_main
      no_log: true

    # ------------------------------------------------------------
    # 3) Print authoritative MAIN data
    # ------------------------------------------------------------
    - name: Show device data from MAIN branch
      ansible.builtin.debug:
        var: device_main.json
