# netbox_inventory.yml
plugin: netbox.netbox.nb_inventory

# Pull from your custom credential's env injectors
api_endpoint: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

validate_certs: true
config_context: false

group_by:
  - device_roles
  - sites
  - platforms

query_filters:
  - status: active

device_query_filters:
  - has_primary_ip: "true"

