- name: NetBox device webhook - read MAIN and print
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    # ------------------------------------------------------------
    # 1) Assert webhook injected device_data
    # ------------------------------------------------------------
    - name: Assert device_data is present
      ansible.builtin.assert:
        that:
          - device_data is defined
          - device_data.id is defined
        fail_msg: "Webhook payload did not inject device_data.id into the job"

    - name: Set device_id from webhook
      ansible.builtin.set_fact:
        device_id: "{{ device_data.id }}"

    # ------------------------------------------------------------
    # 2) Read NetBox connection info from environment (AAP credential)
    # ------------------------------------------------------------
    - name: Read NetBox connection from environment
      ansible.builtin.set_fact:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') | default('', true) }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') | default('', true) }}"

    - name: Assert NetBox connection vars are present
      ansible.builtin.assert:
        that:
          - netbox_url | length > 0
          - netbox_token | length > 0
        fail_msg: "NETBOX_URL / NETBOX_TOKEN not set via AAP credential"

    # ------------------------------------------------------------
    # 3) Fetch device from NetBox MAIN branch
    # ------------------------------------------------------------
    - name: Build NetBox device API URL (MAIN)
      ansible.builtin.set_fact:
        device_api_url: "{{ netbox_url | regex_replace('/$', '') }}/api/dcim/devices/{{ device_id }}/"

    - name: Get device from NetBox MAIN
      ansible.builtin.uri:
        url: "{{ device_api_url }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        return_content: true
        validate_certs: true
        status_code: 200
      register: device_main
      no_log: true

    # ------------------------------------------------------------
    # 4) Print authoritative MAIN data
    # ------------------------------------------------------------
    - name: Show device data from MAIN branch
      ansible.builtin.debug:
        var: device_main.json
