---
- name: NetBox device report
  hosts: all
  gather_facts: false

  tasks:
    - name: Show device info
      ansible.builtin.debug:
        msg:
          - "Name: {{ inventory_hostname }}"
          - "Region: {{ nb_region | default('N/A') }}"
          - "Site: {{ nb_site | default('N/A') }}"
          - "Location: {{ nb_location | default('N/A') }}"
          - "Device Type: {{ nb_device_type | default('N/A') }}"
          - "Tenant: {{ nb_tenant | default('N/A') }}"

