---
- name: NetBox device report
  hosts: all
  gather_facts: false

  tasks:
    - name: Print a line per device
      ansible.builtin.debug:
        msg:
          - "Name: {{ inventory_hostname }}"
          - "Region: {{ nb_region | default('N/A') }}"
          - "Site: {{ nb_site | default('N/A') }}"
          - "Location: {{ nb_location | default('N/A') }}"
          - "Device Type: {{ nb_device_type | default('N/A') }}"
          - "Tenant: {{ nb_tenant | default('N/A') }}"

    - name: Write CSV report to project workspace
      run_once: true
      delegate_to: localhost
      vars:
        _hosts: "{{ groups['all'] | list }}"
      ansible.builtin.copy:
        dest: /runner/project/device_report.csv
        mode: "0644"
        content: |
          name,region,site,location,device_type,tenant
          {% for h in _hosts %}
          {{ h | replace(',', ' ') }},
          {{ (hostvars[h].nb_region | default('')) | replace(',', ' ') }},
          {{ (hostvars[h].nb_site | default('')) | replace(',', ' ') }},
          {{ (hostvars[h].nb_location | default('')) | replace(',', ' ') }},
          {{ (hostvars[h].nb_device_type | default('')) | replace(',', ' ') }},
          {{ (hostvars[h].nb_tenant | default('')) | replace(',', ' ') }}
          {% endfor %}

